// Lessons on natural numbers, Peano arithmetic, booleans as a
// data type, a program as a database, and lists built from cons/nil.
import { md, program, query, exercise, lesson } from './dsl.js';

export const naturals = lesson({
  id: 'naturals',
  part: 'Data & computation',
  title: 'Natural numbers and Peano',
  summary:
    'Numbers as terms: z and s/1, the nat/1 and sum/3 relations, and equations that run both ways.',
  blocks: [
    md(`
### No types in logic programming

In **pure** logic programming, \`3\` and \`+\` are just symbols, with no specific meaning attached, and the same holds in pure Prolog. So how do we deal with, say, **natural numbers**? Giuseppe Peano shows us the way.

#### Peano axioms

The five **Peano axioms**, also known as Peano's postulates, were introduced in 1889 by the Italian mathematician Giuseppe Peano. Like Euclid's axioms for geometry, they were meant to provide a rigorous foundation for the natural numbers (0, 1, 2, 3, ...) used in arithmetic, number theory and set theory. In particular, they enable an **infinite set to be generated by a finite set of symbols and rules**.

1. **Zero** is a natural number.
2. Every natural number has a **successor** in the natural numbers.
3. Zero is **not** the successor of any natural number.
4. If the successor of two natural numbers is the same, then the two original numbers are the **same**.
5. If a set contains zero and the successor of every number is in the set, then the set contains the natural numbers (**induction**).

### Natural numbers in logic programming

In logic programming, the **Herbrand universe** represents the elements of the domain of discourse, and the **Herbrand base** represents the elementary propositions over the domain of discourse. To represent natural numbers we therefore use **constants and functors** for the numbers, and **predicates** for relations such as \`n ∈ ℕ\`.

Our domain of discourse is ℕ, so our Herbrand universe needs to express the elements of ℕ. From the Peano axioms we understand that:

- **zero** is essential: we use \`z\` as the constant symbol for zero. This is *not* something belonging to the language, it is just our (pre-)interpretation of the symbol \`z\` for our current purposes;
- the notion of **successor** is essential, too: we use \`s/1\` (\`s\` with arity 1) as the functor symbol for successor. If \`N\` is a natural number, then \`s(N)\` is another natural number, precisely the successor of \`N\`. This is a **recursive data structure**: the successor of \`s(N)\` is \`s(s(N))\`, which is another natural number.

In our pre-interpretation, \`z\` is zero, \`s(z)\` is one, \`s(s(z))\` is two, and so on.

We focus on the simple relation \`n ∈ ℕ\`, that is, "n is a natural number", and we use \`nat/1\` as its predicate symbol. If \`N\` is a variable, the atom \`nat(N)\` represents the proposition "N is a natural number", according to our current interpretation. For instance, \`nat(s(s(z)))\` means that *two is a natural number*.

### Natural numbers in Prolog

A first program, the **extensional** representation: one fact per number.

\`\`\`prolog
nat(z).         % zero is a natural number
nat(s(z)).      % one is a natural number
nat(s(s(z))).   % two is a natural number
...
\`\`\`

It needs an **infinite number of clauses** (facts) for infinite numbers, which is not exactly in the spirit of axiomatic systems, in particular of Peano's one: we just used facts. **Rules** are what trigger the *intensional* representation, with universal variables: a finite representation for (potentially) infinite propositions.

A second program (\`naturals.pl\`) uses a **recursive rule** for the intensional representation: one fact and one rule for infinitely many numbers.
`),
    program(
      `nat(z).               % zero is a natural number
nat(s(N)) :- nat(N). % if N is a natural number, then
                      % its successor is a natural number`,
      { fresh: true, title: 'naturals.pl (nat/1)' },
    ),
    query('nat(z)', { expect: ['true'] }),
    query('nat(0)', { expect: ['false'] }),
    query('nat(s(s(s(s(s(s(z)))))))', { expect: ['true'] }),
    query('nat(N)', {
      max: 5,
      expect: ['N = z', 'N = s(z)', 'N = s(s(z))', 'N = s(s(s(z)))', 'N = s(s(s(s(z))))'],
    }),
    query('nat(s(N))', { max: 4 }),
    md(`
Remarks:

- **\`z\` is zero, \`0\` is not zero.** \`0\` is an integer, a different term altogether.
- Recursive data structures are powerful and expressive, yet **unreadable for humans**, and generally impractical. This is why Prolog is actually *impure* logic programming, with predicates like \`?- X is 1 + 3.\`
- Logic programming allows for the **generation of data**, e.g. the set of natural numbers, or the set of positive numbers (\`nat(s(N))\`).
- There is an **unlimited number of SLD refutations**: an infinite branch of the proof tree.
- **The order of clauses matters in Prolog.** What if we exchange the fact with the rule?
`),
    program(
      `nat2(s(N)) :- nat2(N).   % the rule first ...
nat2(z).                 % ... and the fact last`,
      { title: 'nat2: clauses swapped' },
    ),
    query('nat2(s(s(z)))', { expect: ['true'] }),
    query('nat2(N)', { error: true }),
    md(`
Checking a *given* number still works, but asking for **any** \`nat2(N)\` dives into the recursive rule forever without ever reaching the fact: with the clauses swapped, the generator never produces a first answer. The fact for the base case must come **before** the recursive rule.

### Computing with naturals: sum/3

File \`naturals.pl\` continues with the sum, based on the same representation of ℕ:

\`\`\`prolog
sum(z, N, N).                   % zero plus N is N
sum(s(M), N, s(P)) :- sum(M, N, P).  % if M plus N is P, then adding N to
                                     % the successor of M returns the successor of P
\`\`\`

\`sum/3\` actually represents an **equation** in the form of a ternary relation: \`sum(X, Y, Z)\` means that \`X + Y = Z\`.
`),
    program(
      `sum(z, N, N).                 % zero plus N is N
sum(s(M), N, s(P)) :-         % if M plus N is P, then
    sum(M, N, P).             % adding N to the successor of M
                              % returns the successor of P`,
      { fresh: true, title: 'naturals.pl (sum/3)' },
    ),
    query('sum(s(z), s(s(z)), S)', { expect: ['S = s(s(s(z)))'] }),
    query('sum(0, s(0), S)', { expect: ['false'] }),
    query('sum(X, s(s(z)), s(s(s(s(s(s(z)))))))', { expect: ['X = s(s(s(s(z))))'] }),
    query('sum(s(s(s(s(z)))), Y, s(s(s(s(s(s(z)))))))', { expect: ['Y = s(s(z))'] }),
    query('sum(X, Y, s(s(s(s(s(s(z)))))))', { max: 10 }),
    query('sum(X, s(s(z)), Y), sum(X, Y, s(s(s(s(s(s(z)))))))', { max: 2, limited: true }),
    md(`
Remarks:

- again, \`z\` is zero and \`0\` is **not** zero (so goal 2 fails);
- there are **no predefined input/output parameters** for the \`sum/3\` procedure: atoms represent **equations**;
- the system can **generate** possible solutions (goal 5 lists all 7 ways to split 6);
- equations can be **combined in systems of equations** (goal 6). It finds \`X = 2, Y = 4\`, and then keeps searching for more solutions forever: the notebook stops it after a bounded number of steps.
`),
    exercise({
      title: 'Double a natural',
      prompt: `
Using \`z\` and \`s/1\`, write \`double(N, D)\`: \`D\` is twice the natural number \`N\`. For example \`double(s(s(z)), D)\` gives \`D = s(s(s(s(z))))\`. You may call \`sum/3\` (already loaded).
`,
      setup: `sum(z, N, N).
sum(s(M), N, s(P)) :- sum(M, N, P).`,
      starter: '% double(N, D) :- ...\n',
      hint: 'Doubling is adding a number to itself: `double(N, D) :- sum(N, N, D).`',
      solution: 'double(N, D) :- sum(N, N, D).',
      tests: [
        { q: 'double(z, D)', expect: ['D = z'] },
        { q: 'double(s(s(z)), D)', expect: ['D = s(s(s(s(z))))'] },
        { q: 'double(N, s(s(s(s(z)))))', expect: ['N = s(s(z))'] },
      ],
    }),
  ],
});

export const peano = lesson({
  id: 'peano',
  part: 'Data & computation',
  title: 'Peano arithmetic',
  summary:
    'succ, sum, mul, dec and factorial on zero and s/1, plus predicates as boolean functions.',
  blocks: [
    md(`
### Programming data types

A **data type** is a **construction** plus **algorithms**. The *construction* is defined by deciding the functors (name and arity) for the terms; the *algorithms* are predicates, with a mapping from functions to relations.

Recall the features of an **algebraic data type**: a name for the type; a set of *values*, expressed by sums of products; and a set of I/O pure *functions*, often using recursion.

In Prolog we have **no types**, hence no enforcement:

- the **name** can only impact the names of values and functions;
- **values** are expressed by a set of functors, e.g. \`cons/2\` and \`nil/0\`;
- a **function** \`f : I1, I2, ..., In ↦ O\` becomes a predicate \`p(I1, I2, ..., In, O)\`. Functions are defined (in the body) as a **composition of goals**: \`h(X) = f(g(X))\` becomes \`h(X, Y) :- g(X, Z), f(Z, Y).\` ideally using matching on functors. Functions *returning booleans* might have special treatment.

### Example: naturals by Peano numbers

Encoding natural numbers is traditionally the next step after booleans while studying a language's expressiveness. An easy encoding is the unary, Peano one: \`Z, SZ, SSZ, SSSZ, SSSSZ, ...\`, so for instance \`SSZ + SSSZ = SSSSSZ\`. (Prolog will actually have an ad-hoc management of numbers and booleans.)

The ideas:

- use the functors \`s/1\` and \`zero/0\`, e.g. \`s(s(s(zero)))\`;
- the \`succ\` function is easily obtained by \`s/1\` construction;
- \`sum\` is obtained recursively from \`succ\` or \`s/1\`: \`a + 0 = a\`, \`a + s(b) = s(a + b)\`;
- \`mul\` is obtained recursively from \`sum\`: \`a * 0 = 0\`, \`a * s(b) = a + (a * b)\`;
- we should be able to implement **factorial**;
- the output is the last argument, as usual.

The solution (\`peano.pl\`):
`),
    program(
      `succ(X, s(X)).

sum(X, zero, X).
sum(X, s(Y), s(Z)) :- sum(X, Y, Z).

mul(_, zero, zero).
mul(X, s(Y), Z) :- mul(X, Y, W), sum(W, X, Z).

dec(s(X), X).

factorial(zero, s(zero)).
factorial(s(X), Y) :- factorial(X, Z), mul(s(X), Z, Y).`,
      { fresh: true, title: 'peano.pl' },
    ),
    md(`
How to read the specification in the **relational interpretation**:

- the successor of \`X\` is \`s(X)\`;
- the sum of \`X\` and \`zero\` is \`X\`;
- the sum of \`X\` and the successor of \`Y\` is the successor of \`Z\`, provided the sum of \`X\` and \`Y\` is \`Z\`;
- et cetera.

> [!note] \`succ/2\` and \`plus/3\` are library predicates of SWI-Prolog. Defining your own in a program is fine here: the clauses of your program take precedence.

The goals:
`),
    query('succ(s(s(zero)), N)', { expect: ['N = s(s(s(zero)))'] }),
    query('sum(s(s(s(zero))), s(s(zero)), N)', { expect: ['N = s(s(s(s(s(zero)))))'] }),
    query('mul(s(s(zero)), s(s(zero)), N)', { expect: ['N = s(s(s(s(zero))))'] }),
    query('dec(s(s(zero)), N)', { expect: ['N = s(zero)'] }),
    query('dec(zero, N)', { expect: ['false'] }),
    query('sum(N, M, s(s(s(zero))))', {
      expect: [
        'N = s(s(s(zero))), M = zero',
        'N = s(s(zero)), M = s(zero)',
        'N = s(zero), M = s(s(zero))',
        'N = zero, M = s(s(s(zero)))',
      ],
    }),
    md(`
The last goal shows the **relational** nature of the encoding: \`sum\` run backwards enumerates *every* pair of naturals adding up to 3.

The resolution of \`sum(s(s(s(zero))), s(s(zero)), N)\` unfolds as:

\`\`\`
sum(s(s(s(zero))), s(s(zero)), N)
sum(s(s(s(zero))), s(zero), Z') : {N/s(Z')}
sum(s(s(s(zero))), zero, Z'')   : {N/s(Z'), Z'/s(Z'')} ≡ {N/s(s(Z''))}
{N/s(Z'), Z'/s(Z''), Z''/s(s(s(zero)))} ≡ {N/s(s(s(s(s(zero)))))}
\`\`\`

The factorial, which the program is built for:
`),
    query('factorial(s(s(s(zero))), F)', { expect: ['F = s(s(s(s(s(s(zero))))))'] }),
    md(`
### Functions returning a boolean

File \`greater.pl\`. The typical Prolog approach is **not** to add an argument being \`b_true\` or \`b_false\`, but rather: \`f : I1, I2, ..., In ↦ bool\` becomes \`p(I1, I2, ..., In)\`, and the result is **whether the call to the predicate fails or succeeds**. In fact, one such function *is* a predicate. This way, we can only implement what should happen in the **positive** cases.
`),
    program(
      `greater(s(_), zero).
greater(s(N), s(M)) :- greater(N, M).`,
      { title: 'greater.pl' },
    ),
    query('greater(s(zero), s(zero))', { expect: ['false'] }),
    query('greater(s(s(zero)), s(zero))', { expect: ['true'] }),
    md(`
### Multiple output arguments

File \`nextprev.pl\`. Again, rather than an output of type *pair*: \`f : I1, ..., In ↦ O1 × O2\` becomes \`p(I1, ..., In, O1, O2)\`. In fact, we can conceptually have **many inputs and many outputs**.
`),
    program('nextprev(s(N), N, s(s(N))).', { title: 'nextprev.pl' }),
    query('nextprev(s(s(zero)), Prev, Next)', { expect: ['Prev = s(zero), Next = s(s(s(zero)))'] }),
    query('nextprev(zero, Prev, Next)', { expect: ['false'] }),
    md(`
### Multiple results

File \`range.pl\`. Typically in Prolog, a function returning a *lazy list*, \`f : I1, ..., In ↦ LazyList\`, becomes \`p(I1, ..., In, O)\` such that it provides **multiple solutions** through the inherent resolution mechanism. We should always be prepared for goals to admit many solutions.
`),
    program(
      `% greater/2 is repeated from greater.pl, which range/3 calls.
greater(s(_), zero).
greater(s(N), s(M)) :- greater(N, M).

range(N1, _, N1).
range(N1, N2, N) :- greater(N2, N1), range(s(N1), N2, N).`,
      { fresh: true, title: 'range.pl' },
    ),
    query('range(zero, s(s(s(zero))), N)', {
      expect: ['N = zero', 'N = s(zero)', 'N = s(s(zero))', 'N = s(s(s(zero)))'],
    }),
    md(`
The resolution tree of \`range(zero, s(s(s(zero))), N)\` produces one solution per level, then fails on the last level because \`greater\` no longer holds:

\`\`\`
range(zero, 3, N)
├── {N/zero}
└── greater(3, zero), range(s(zero), 3, N)
    ├── {N/s(zero)}
    └── greater(3, 1), range(s(s(zero)), 3, N)
        ├── {N/s(s(zero))}
        └── greater(3, 2), range(s(s(s(zero))), 3, N)
            ├── {N/s(s(s(zero)))}
            └── greater(3, 3), ...   → No
\`\`\`
`),
    exercise({
      title: 'Less than or equal',
      prompt: `
The Peano \`greater/2\` is loaded. Write \`less_or_equal(A, B)\`: it succeeds when the Peano number \`A\` is less than or equal to \`B\` (that is, **not** \`greater(A, B)\`), as a plain predicate returning success or failure.
`,
      setup: `greater(s(_), zero).
greater(s(N), s(M)) :- greater(N, M).`,
      starter: '% less_or_equal(A, B) :- ...\n',
      hint: 'Two facts-and-a-rule in the style of `greater`: `zero` is below everything, and `s(A) <= s(B)` when `A <= B`.',
      solution: `less_or_equal(zero, _).
less_or_equal(s(A), s(B)) :- less_or_equal(A, B).`,
      tests: [
        { q: 'less_or_equal(zero, zero)', expect: ['true'] },
        { q: 'less_or_equal(s(zero), s(s(zero)))', expect: ['true'] },
        { q: 'less_or_equal(s(s(zero)), s(zero))', expect: ['false'] },
        { q: 'less_or_equal(s(s(zero)), s(s(zero)))', expect: ['true'] },
      ],
    }),
  ],
});

export const booleans = lesson({
  id: 'booleans',
  part: 'Data & computation',
  title: 'Booleans as a data type',
  summary: 'Propositional logic as universal facts, then improved with rules.',
  blocks: [
    md(`
### A recap example: modelling propositional logic

File \`booleans-facts.pl\`. The modelling idea is that this is a simple **data type**:

- we have two booleans, modelled as atomic terms \`b_true\` and \`b_false\` (functors with arity 0);
- a **unary function** is modelled as a binary predicate \`p(I, O)\`;
- a **binary function** is modelled as a ternary predicate \`p(I1, I2, O)\`;
- use **universal facts** to somewhat address DRY (don't repeat yourself).

Can we derive a general approach for data types?
`),
    program(
      `b_not(b_true, b_false).
b_not(b_false, b_true).

b_and(B, b_true, B).
b_and(_, b_false, b_false).

b_or(B, b_false, B).
b_or(_, b_true, b_true).`,
      { fresh: true, title: 'booleans-facts.pl' },
    ),
    query('b_not(b_false, B)', { expect: ['B = b_true'] }),
    query('b_and(b_false, b_true, B)', { expect: ['B = b_false'] }),
    query('b_or(b_false, b_true, B)', { expect: ['B = b_true'] }),
    query('b_or(b_true, B2, B)', {
      expect: ['B2 = b_false, B = b_true', 'B2 = b_true, B = b_true'],
    }),
    query('b_or(B1, B2, B)', {
      expect: ['B1 = B, B2 = b_false', 'B2 = b_true, B = b_true'],
    }),
    md(`
The last two goals are the interesting ones. \`b_or(b_true, B2, B)\` has **two** answers: whatever \`B2\` is, the result is \`b_true\`, because the first argument is true. And \`b_or(B1, B2, B)\` is the whole truth table of *or* in two clauses: either \`B2\` is false and the result is just \`B1\`, or \`B2\` is true and the result is true.

### Improving booleans with rules

File \`booleans-rules.pl\`. The same booleans, with \`b_or\` and \`b_implies\` as **rules**, defined by composing the other functions:
`),
    program(
      `b_not(b_true, b_false).
b_not(b_false, b_true).

b_and(B, b_true, B).
b_and(_, b_false, b_false).

b_or(B1, B2, B) :-          % (a or b) = !(!a and !b)
    b_not(B1, NB1), b_not(B2, NB2),
    b_and(NB1, NB2, NB), b_not(NB, B).

b_implies(B1, B2, B) :-     % a --> b = !a or b
    b_not(B1, NB1), b_or(NB1, B2, B).`,
      { fresh: true, title: 'booleans-rules.pl' },
    ),
    query('b_implies(b_true, b_false, O)', { expect: ['O = b_false'] }),
    query('b_implies(b_false, b_false, O)', { expect: ['O = b_true'] }),
    md(`
The resolution of \`b_implies(b_true, b_false, O)\`, one resolvent per line:

\`\`\`
b_implies(b_true, b_false, O)
b_not(b_true, NB1'), b_or(NB1', b_false, O)
b_or(b_false, b_false, O)
b_not(b_false, NB1'), b_not(b_false, NB2'), b_and(NB1', NB2', NB'), b_not(NB', O)
b_not(b_false, NB2'), b_and(b_true, NB2', NB'), b_not(NB', O)
b_and(b_true, b_true, NB'), b_not(NB', O)
b_not(b_true, O)

{O/b_false}
\`\`\`

This is the **procedural interpretation** at work: each goal of a body is replaced, in turn, by the body of a matching clause, until the resolvent is empty, and the substitution is the result.
`),
    exercise({
      title: 'Exclusive or',
      prompt: `
The booleans of the rule-based file are loaded (\`b_not/2\`, \`b_and/3\`, \`b_or/3\`). Write \`b_xor(B1, B2, B)\`: exclusive or, defined **by composing** the other functions as \`(a or b) and not (a and b)\`.
`,
      setup: `b_not(b_true, b_false).
b_not(b_false, b_true).
b_and(B, b_true, B).
b_and(_, b_false, b_false).
b_or(B1, B2, B) :-
    b_not(B1, NB1), b_not(B2, NB2),
    b_and(NB1, NB2, NB), b_not(NB, B).`,
      starter: '% b_xor(B1, B2, B) :- ...\n',
      hint: 'Compute `b_or(B1, B2, O)`, `b_and(B1, B2, A)`, `b_not(A, NA)`, then `b_and(O, NA, B)`.',
      solution: `b_xor(B1, B2, B) :-
    b_or(B1, B2, O), b_and(B1, B2, A), b_not(A, NA), b_and(O, NA, B).`,
      tests: [
        { q: 'b_xor(b_true, b_true, B)', expect: ['B = b_false'] },
        { q: 'b_xor(b_true, b_false, B)', expect: ['B = b_true'] },
        { q: 'b_xor(b_false, b_true, B)', expect: ['B = b_true'] },
        { q: 'b_xor(b_false, b_false, B)', expect: ['B = b_false'] },
      ],
    }),
  ],
});

export const dbpatterns = lesson({
  id: 'dbpatterns',
  part: 'Data & computation',
  title: 'A program as a database',
  summary: 'Querying facts, existential and universal queries, records and the wildcard variable.',
  blocks: [
    md(`
### Logic programming patterns

The most relevant elements of Prolog as a programming language, with some useful programming (and design) patterns:

- querying facts, existential queries, querying universal facts;
- working with records, wildcard variables;
- deriving knowledge with rules;
- programming maths, and programming data types such as lists.

#### A Prolog program as a DB

- **Querying facts.** A Prolog program with only **ground facts** can be seen as a database: all facts of a certain predicate (name and arity) form a *table*, and a single ground goal can be used to query the DB for a tuple.
- **Existential queries.** If the goal has variables, you are really asking whether there **exists** an instantiation of the variables (a substitution) equating your goal with one or more facts. This is like searching multiple tuples with one query, and composing goals makes Prolog find **combinations**.
- **Universal facts.** Variables in facts are quantified **universally** instead, hence a fact with variables is like an *infinite set of facts*.
- **Working with records.** A fact can connect terms which are structured, e.g. in the form of records.
- **The wildcard variable**, to avoid mentioning a variable once in a clause.

### Querying facts

File \`querying-facts.pl\`.
`),
    program(
      `male(isaac).
plus(2, 3, 5).
plus(1, 6, 7).
plus(0, 0, 5).`,
      { fresh: true, title: 'querying-facts.pl' },
    ),
    query('plus(2, 3, 5)', { expect: ['true'] }),
    query('male(isaac)', { expect: ['true'] }),
    query('plus(0, 0, 0)', { expect: ['false'] }),
    query('plus(2, 3, 5), plus(1, 6, 7)', { expect: ['true'] }),
    md(`
In resolution trees, *yes* is used to mean an empty resolvent (sometimes avoided altogether), and when there is no solution a *no* label is added. The tree for \`plus(2,3,5), plus(1,6,7)\` has a single branch: the first goal is solved, and the resolvent shrinks to \`plus(1,6,7)\`, then to the empty one.

### Existential queries

File \`existential-queries.pl\`. Each branch of the tree corresponds to a rule or fact unifying with the goal, and the unifier is taken as a solution.
`),
    program(
      `plus(2, 3, 5).
plus(1, 6, 7).
plus(0, 0, 5).`,
      { fresh: true, title: 'existential-queries.pl' },
    ),
    query('plus(0, X, Y)', { expect: ['X = 0, Y = 5'] }),
    query('plus(X, Y, 5)', { expect: ['X = 2, Y = 3', 'X = 0, Y = 0'] }),
    query('plus(X, Y, Y)', { expect: ['false'] }),
    md(`
#### Existential queries and inherent exploration

**Solving multiple goals inherently explores combinations**, a bit like multiple clauses in a for-comprehension. Here, for each solution of the first goal, the second goal is explored in full:
`),
    query('plus(X, Y, Z), plus(W, K, Z)', { max: 5 }),
    md(`
### Universal facts

File \`universal-facts.pl\`. A variable in a fact stands for infinitely many facts: unification with a universal fact creates a substitution mentioning variables of a **cloned** clause, which are not shown in the final result.
`),
    program(
      `plus(0, X, X).
plus(X, 0, X).`,
      { fresh: true, title: 'universal-facts.pl' },
    ),
    query('plus(0, 3, 3)', { expect: ['true'] }),
    query('plus(0, 5, R)', { expect: ['R = 5'] }),
    query('plus(3, 0, X)', { expect: ['X = 3'] }),
    query('plus(0, 0, X)', { expect: ['X = 0', 'X = 0'] }),
    md(`
\`plus(3, 0, X)\` has **no clash**: the variable \`X\` of the first clause is a *different* variable from the one in the goal, thanks to renaming. And \`plus(0, 0, X)\` answers \`X = 0\` **twice**, once per universal fact: both clauses apply.

### Working with records

File \`records.pl\`. A fact can relate **structured** terms. Recall that \`manager\` is a predicate, \`person\` a functor. Prolog prints the minimal substitution.
`),
    program(
      `manager(person(john, smith, 1283)).
clerk(person(jim, white, 3475)).
clerk(person(george, red, 8765)).
chief(person(john, smith, 1283), person(george, red, 8765)).`,
      { fresh: true, title: 'records.pl' },
    ),
    query('chief(X, person(Y, Z, 8765))', {
      expect: ['X = person(john, smith, 1283), Y = george, Z = red'],
    }),
    md(`
### The wildcard variable

File \`wildcard.pl\`.

- In **programs**, \`_\` marks a variable used **once** in the clause.
- In **goals**, it marks a variable we do not need to see in the solutions.

It is good Prolog practice to **never use singleton variables** in a clause, but wildcards instead. This avoids copy-and-paste errors in variable names.
`),
    program(
      `p(_, 1).
p(1, 2).
q(_, a(1, _)).
r(X, a(1, X)).`,
      { fresh: true, title: 'wildcard.pl' },
    ),
    query('p(X, 1)', { expect: ['true'] }),
    query('p(1, Y)', { expect: ['Y = 1', 'Y = 2'] }),
    query('p(1, _)', { expect: ['true', 'true'] }),
    query('q(1, a(1, 2))', { expect: ['true'] }),
    query('r(1, a(1, 2))', { expect: ['false'] }),
    md(`
\`p(1, _)\` answers *yes* twice (both clauses match, and nothing is displayed for \`_\`). \`r(1, a(1, 2))\` fails: unlike \`q\`, \`r\` repeats \`X\`, so the two positions must agree, and \`1 ≠ 2\`.
`),
    exercise({
      title: 'Records and a wildcard',
      prompt: `
The \`clerk/1\` and \`manager/1\` records are loaded. Write \`first_names(F)\`: it should list the first names of the clerks, one per solution, using wildcards for the fields you do not need.
`,
      setup: `manager(person(john, smith, 1283)).
clerk(person(jim, white, 3475)).
clerk(person(george, red, 8765)).`,
      starter: '% first_names(F) :- ...\n',
      hint: 'A single rule is enough: `first_names(F) :- clerk(person(F, _, _)).`',
      solution: 'first_names(F) :- clerk(person(F, _, _)).',
      tests: [
        { q: 'first_names(F)', expect: ['F = jim', 'F = george'] },
        { q: 'first_names(john)', expect: ['false'] },
      ],
    }),
  ],
});
